parameters:
  - name: test_postmanCollection_SIT
    type: string
    default: ""
  - name: test_postmanEnvironment_SIT
    type: string
    default: ""
  - name: test_additionalParams_SIT
    type: string
    default: ""
  - name: test_testReportTitle_SIT
    type: string
    default: ""
  - name: test_postmanCollection_UAT
    type: string
    default: ""
  - name: test_postmanEnvironment_UAT
    type: string
    default: ""
  - name: test_additionalParams_UAT
    type: string
    default: ""
  - name: test_testReportTitle_UAT
    type: string
    default: ""
  - name: process_version
    type: string
    default: ""

stages:
  - stage: Build
    displayName: "Build Deployed Package"
    jobs:
      - template: build_job_template.yml
        parameters:
          jobName: "Create Package"
          process_version: ${{ parameters.process_version }}
          buildReason: ${{ variables['Build.Reason'] }}

