parameters:
  - name: jobName
    type: string
    default: "Autotests"
  - name: process_version
    type: string
    default: ""

jobs:
  - job: Job_1
    displayName: "Running autotests..."
    steps:
      - script: |
            #!/bin/bash
            echo "[INFO] Inside the build_job_template.yml - ${{ parameters.process_version }}"
